### ISSUE TITLE
Browser client requests fail due to unsupported Content-Type `application/grpc-web-text`

### ISSUE THREAD

**Issue by jannisch** [InfluxCommunity/influxdb3-js#370]
### Specifications

* Client Version: 0.9.0
* InfluxDB Version: 3.0 IOx Serverless
* Platform: CloudFlare Workers (V8, [runtime apis](https://developers.cloudflare.com/workers/runtime-apis/))

### Code sample to reproduce problem

```typescript
import { InfluxDBClient } from "@influxdata/influxdb3-client"

interface Env {
    INFLUX_TOKEN: string
    INFLUX_DB: string
}

export default {
    async fetch(request: Request, env: Env): Promise<Response> {
        const influx = new InfluxDBClient({
            host: "https://eu-central-1-1.aws.cloud2.influxdata.com",
            token: env.INFLUX_TOKEN,
            database: env.INFLUX_DB
        })

        const res = await influx.query("SELECT * FROM foo")

        const data = []

        for await (const value of res) {
            data.push(value)
        }

        return Response.json(data)
    }
} satisfies ExportedHandler<Env>

```

### Expected behavior

Respond with query results

### Actual behavior

```
RpcError: invalid gRPC request content-type "application/grpc-web-text"
  at null.<anonymous>
  (file:///C:/Users/jannisch/source/influx-worker/node_modules/@protobuf-ts/grpcweb-transport/build/es2015/grpc-web-transport.js:62:23)
  {
    code: 'INVALID_ARGUMENT',
    meta: {
      connection: 'keep-alive',
      'content-length': '0',
      date: 'Wed, 24 Jul 2024 23:54:46 GMT',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-envoy-upstream-service-time': '0'
    },
    methodName: 'DoGet',
    serviceName: 'arrow.flight.protocol.FlightService'
  }
```

### Additional info

Same behaviour with @influxdata/influxdb3-client-**browser**

**Comment by jannisch** [comment]
I'm wondering how this could have ever worked before ?

**Comment by bednar** [comment]
Hi @jannisch,

Thank you for choosing our client for your application.

I understand you are using the `influxdb3-client-browser`, which is specifically designed to operate within a browser environment. It’s important to ensure that you have a properly configured proxy to facilitate the client's operations, especially since it makes use of gRPC calls to communicate with InfluxDB 3.

For a step-by-step guide on setting up the client in a browser environment, including examples that might help you configure your setup more effectively, please visit our documentation here: [Browser Examples](https://github.com/InfluxCommunity/influxdb3-js/tree/main/examples/browser).

Regarding the configuration of your Cloudflare environment to support gRPC:
- Cloudflare does offer support for gRPC, allowing you to leverage the benefits of gRPC’s performance and efficiency in web communications. However, it requires specific settings to be enabled and configured properly.
- You can find detailed instructions and recommendations on setting up gRPC with Cloudflare in their official documentation here: [Configuring gRPC Connections on Cloudflare](https://developers.cloudflare.com/network/grpc-connections/).

Please ensure that Cloudflare’s gRPC settings are correctly configured to avoid connection issues or disruptions in service. This includes checking any relevant firewall settings, SSL/TLS configurations, and ensuring that your Cloudflare settings are compatible with gRPC's requirements.

If you have further questions or encounter specific issues while setting this up, feel free to share more details or error messages, and I’ll be more than happy to assist you further.

Best Regards

**Comment by jannisch** [comment]
Thanks a lot for your reply. While I thought it is AI generated at first, it is quite helpful since you do provide an example for such a proxy. If I am not mistaken, the proxy is generally required, as the client could support only HTTP/1.1, i.ey in the case of an outdated browser. On the other hand, one does control the environment when building an app using Deno, Bun, etc, just as in the case of Node.JS, where we know that the supported version supports HTTP/2. So it would be a nice feature enhancement in fact to be able to use the direct gRPC transport with in the browser sdk, correct?

**Comment by bednar** [comment]
Hi @jannisch,

As I mentioned, the proxy is required due to the browser environment. For more information, see - https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md.

Best regards

**Comment by jannisch** [comment]
I am going to close this issue as it is a non-issue with browsers in fact.

However what I tried to point out that deno and other runtimes (which you already [support](https://github.com/InfluxCommunity/influxdb3-js/blob/c4c8d1ca40e406b88c1da244645353c915dc054c/packages/client-browser/package.json#L27)) are not browser environments. They are rather like Node.js as we deploy them but with the same APIs as the browser, hence I don't understand the need for the proxy.
